version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket_express
    # we use volumes because if we down the container , the data will be deleted but by doing this we save it inside volumes
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine

    ports:
      - "6379:6379"

volumes:
  postgres_data:
